---
name: Tie-UnionHash
version: 0.01
author:
  - 'Zahatski Aliaksandr, <zag@cpan.org>'
abstract: Union hashes. Make changes to the last hash in arguments ( depend on option <freeze_keys>).
license: perl
resources:
  license: http://dev.perl.org/licenses/
provides:
  Tie::UnionHash:
    file: lib/Tie/UnionHash.pm
    version: 0.01
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
